file_format: "1"
id: sofle
name: SOFLE
type: shield
url: https://github.com/Bastardkb/TBK-Mini
requires: [Nice!Nano]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - sofle_left
  - sofle_right
